# Generated by Django 5.2.9 on 2026-01-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_player_userprofile_telegram_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pdn_consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pdn_consent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='PDNActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('export', 'Выгрузка персональных данных'), ('anonymize', 'Анонимизация персональных данных'), ('update_profile', 'Обновление профиля пользователя'), ('change_password', 'Смена пароля пользователя'), ('link_player', 'Связь пользователя с игроком'), ('unlink_player', 'Отвязка игрока от пользователя'), ('create_player', 'Создание игрока пользователем')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdn_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Операция с ПДн',
                'verbose_name_plural': 'Операции с ПДн',
                'ordering': ['-created_at'],
            },
        ),
    ]
