# Generated by Django 5.2.9 on 2026-04-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_pdn_consent_given_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetSupportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("IN_PROGRESS", "В работе"),
                            ("DONE", "Закрыта"),
                            ("REJECTED", "Отклонена"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Заметка")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User-Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_password_reset_support_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_reset_support_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на сброс пароля",
                "verbose_name_plural": "Заявки на сброс пароля",
                "ordering": ["-created_at"],
            },
        ),
    ]
