FROM nginx:1.25-alpine

# Копируем конфигурацию Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Создаем директории для логов
RUN mkdir -p /var/log/nginx

# Healthcheck
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost/api/health/ || exit 1

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
