[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
include_trailing_comma = true

[tool.flake8]
max-line-length = 100
select = ["E", "F", "W"]
extend-ignore = [
  "E203",  # whitespace before ':', конфликт с black
  "W503",  # line break before binary operator, конфликт с black
]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  ".venv",
  "venv",
  "env",
  "migrations",
]