# Generated by Django 5.2.7 on 2025-11-04 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='group_schedule_patterns',
            field=models.JSONField(blank=True, default=dict, help_text='Сопоставление названия группы с ID выбранного шаблона расписания', verbose_name='Шаблоны расписания для групп'),
        ),
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('pattern_type', models.CharField(choices=[('berger', 'Алгоритм Бергера'), ('snake', 'Змейка'), ('custom', 'Кастомный шаблон')], max_length=20, verbose_name='Тип шаблона')),
                ('tournament_system', models.CharField(choices=[('round_robin', 'Круговая система'), ('knockout', 'Олимпийская система')], default='round_robin', help_text='Для какой системы турнира применим этот шаблон', max_length=20, verbose_name='Система турнира')),
                ('description', models.TextField(verbose_name='Описание')),
                ('participants_count', models.IntegerField(blank=True, help_text='Для кастомных шаблонов - обязательно. Для алгоритмических - не используется', null=True, verbose_name='Количество участников')),
                ('custom_schedule', models.JSONField(blank=True, help_text='JSON с описанием туров и пар', null=True, verbose_name='Кастомное расписание')),
                ('is_system', models.BooleanField(default=True, help_text='Системные шаблоны (Berger, Snake) нельзя удалить', verbose_name='Системный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон расписания',
                'verbose_name_plural': 'Шаблоны расписания',
                'ordering': ['tournament_system', 'participants_count', 'is_system', 'name'],
                'unique_together': {('name', 'tournament_system', 'participants_count')},
            },
        ),
    ]
