# Generated by Cascade: state-only migration to register KnockoutBracket and DrawPosition
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_tournament_brackets_count"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="KnockoutBracket",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("index", models.PositiveSmallIntegerField()),
                        ("size", models.PositiveSmallIntegerField()),
                        ("has_third_place", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "tournament",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knockout_brackets", to="tournaments.tournament"),
                        ),
                    ],
                    options={
                        "verbose_name": "Сетка плей-офф",
                        "verbose_name_plural": "Сетки плей-офф",
                    },
                ),
                migrations.AddConstraint(
                    model_name="knockoutbracket",
                    constraint=models.UniqueConstraint(fields=("tournament", "index"), name="uniq_knockout_bracket_in_tournament"),
                ),
                migrations.CreateModel(
                    name="DrawPosition",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("position", models.PositiveSmallIntegerField()),
                        ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                        ("source", models.CharField(choices=[("MAIN", "Main"), ("LL", "Lucky Loser"), ("WC", "Wild Card"), ("Q", "Qualifier"), ("BYE", "Bye")], default="MAIN", max_length=8)),
                        (
                            "bracket",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="positions", to="tournaments.knockoutbracket"),
                        ),
                        (
                            "entry",
                            models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="draw_positions", to="tournaments.tournamententry"),
                        ),
                    ],
                    options={
                        "verbose_name": "Позиция жеребьёвки",
                        "verbose_name_plural": "Позиции жеребьёвки",
                    },
                ),
                migrations.AddConstraint(
                    model_name="drawposition",
                    constraint=models.UniqueConstraint(fields=("bracket", "position"), name="uniq_draw_position_in_bracket"),
                ),
            ],
        )
    ]
