# Generated by Django 5.2.6 on 2025-11-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_group_schedule_patterns_schedulepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='king_calculation_mode',
            field=models.CharField(blank=True, choices=[('g_minus', 'G- (не учитывать лишние матчи)'), ('m_plus', 'M+ (добавить средние за недостающие)'), ('no', 'NO (без компенсации)')], default='g_minus', help_text='Режим компенсации разного количества матчей в турнире Кинг', max_length=10, null=True, verbose_name='Режим подсчета (Кинг)'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='tournament_system',
            field=models.CharField(choices=[('round_robin', 'Круговая система'), ('knockout', 'Олимпийская система'), ('king', 'Кинг')], default='round_robin', help_text='Для какой системы турнира применим этот шаблон', max_length=20, verbose_name='Система турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='system',
            field=models.CharField(choices=[('round_robin', 'Круговая'), ('knockout', 'Олимпийка'), ('king', 'Кинг')], max_length=16),
        ),
    ]
