# Generated by Django 5.2.7 on 2025-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_king_calculation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='tournament_system',
            field=models.CharField(choices=[('round_robin', 'Круговой'), ('knockout', 'Олимпийка'), ('king', 'Кинг')], db_index=True, default='round_robin', help_text='Система турнира, для которой предназначен регламент', max_length=32),
        ),
    ]
