# Generated by Django 5.2.7 on 2025-11-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_ruleset_tournament_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_rating_calc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='parent_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tournaments', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rating_coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='referees',
            field=models.ManyToManyField(blank=True, related_name='tournaments_refereed', to=settings.AUTH_USER_MODEL, verbose_name='Судьи'),
        ),
    ]
