# Generated by Django 5.2.8 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0006_tournament_prize_fund'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamententry',
            name='unique_entry_position',
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='group_index',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='row_index',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='tournamententry',
            constraint=models.UniqueConstraint(condition=models.Q(('group_index__isnull', False), ('row_index__isnull', False)), fields=('tournament', 'group_index', 'row_index'), name='unique_entry_position'),
        ),
    ]
