# Generated by Django 5.2.9 on 2025-12-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_tournamententry_unique_entry_position_and_more'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='venues.venue', verbose_name='Площадка'),
        ),
    ]
