# Generated by Django 5.2.9 on 2025-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
