# Generated by Django 5.2.6 on 2025-12-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_middle_name'),
        ('teams', '0001_initial'),
        ('tournaments', '0009_tournament_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено отправителем')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, help_text='Опциональное сообщение от отправителя', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pair_invitations', to='players.player', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pair_invitations', to='players.player', verbose_name='Отправитель')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_invitations', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Приглашение в пару',
                'verbose_name_plural': 'Приглашения в пары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', 'status'], name='tournaments_tournam_4ceb57_idx'), models.Index(fields=['receiver', 'status'], name='tournaments_receive_b904f3_idx'), models.Index(fields=['sender', 'tournament'], name='tournaments_sender__b62318_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('looking_for_partner', 'Ищет пару'), ('invited', 'Приглашён в пару'), ('main_list', 'Основной состав'), ('reserve_list', 'Резервный список')], default='looking_for_partner', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('registration_order', models.PositiveIntegerField(default=0, help_text='Автоматически заполняется при создании', verbose_name='Порядок регистрации')),
                ('partner', models.ForeignKey(blank=True, help_text='Заполняется когда пара сформирована', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_registrations', to='players.player', verbose_name='Напарник')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='players.player', verbose_name='Игрок')),
                ('team', models.ForeignKey(blank=True, help_text='Ссылка на команду из teams.Team (переиспользуем существующие)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_registrations', to='teams.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Регистрация на турнир',
                'verbose_name_plural': 'Регистрации на турниры',
                'ordering': ['registration_order', 'registered_at'],
                'indexes': [models.Index(fields=['tournament', 'status'], name='tournaments_tournam_b2c279_idx'), models.Index(fields=['player', 'tournament'], name='tournaments_player__fd1e2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player'), name='unique_player_registration_per_tournament')],
            },
        ),
    ]
