# Generated by Django 5.2.9 on 2026-01-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_pairinvitation_tournamentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_from', models.PositiveIntegerField()),
                ('place_to', models.PositiveIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='tournaments.tournamententry')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Место в турнире',
                'verbose_name_plural': 'Места в турнире',
                'ordering': ['place_from', 'place_to', 'id'],
            },
        ),
    ]
