# Generated by Django 5.2.9 on 2026-01-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAnnouncementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(help_text='ID чата или канала для публикации анонсов (например: -1001234567890)', max_length=100, verbose_name='ID чата Telegram')),
                ('send_on_creation', models.BooleanField(default=False, help_text='Отправить анонс сразу после создания турнира', verbose_name='Отправить при создании')),
                ('send_48h_before', models.BooleanField(default=False, help_text='Отправить анонс за 48 часов до начала турнира', verbose_name='Отправить за 48 часов')),
                ('send_24h_before', models.BooleanField(default=True, help_text='Отправить анонс за 24 часа до начала турнира', verbose_name='Отправить за 24 часа')),
                ('send_2h_before', models.BooleanField(default=False, help_text='Отправить анонс за 2 часа до начала турнира', verbose_name='Отправить за 2 часа')),
                ('send_on_roster_change', models.BooleanField(default=False, help_text='Отправить анонс при изменении основного состава участников', verbose_name='Отправить при изменении состава')),
                ('sent_on_creation', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено при создании')),
                ('sent_48h_before', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено за 48 часов')),
                ('sent_24h_before', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено за 24 часа')),
                ('sent_2h_before', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено за 2 часа')),
                ('last_roster_change_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последний анонс изменения состава')),
                ('roster_hash', models.CharField(blank=True, default='', help_text='MD5 хеш списка участников основного состава', max_length=64, verbose_name='Хеш состава')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_settings', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Настройки анонсов турнира',
                'verbose_name_plural': 'Настройки анонсов турниров',
            },
        ),
    ]
