# Generated by Django 5.2.9 on 2026-01-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournamentannouncementsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentannouncementsettings',
            name='send_72h_before',
            field=models.BooleanField(default=False, help_text='Отправить анонс за 72 часа до начала турнира', verbose_name='Отправить за 72 часа'),
        ),
        migrations.AddField(
            model_name='tournamentannouncementsettings',
            name='sent_72h_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено за 72 часа'),
        ),
    ]
