# Generated by Django 5.2.9 on 2026-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_tournamentannouncementsettings_send_72h_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentannouncementsettings',
            name='announcement_mode',
            field=models.CharField(choices=[('new_messages', 'Публиковать новые сообщения'), ('edit_single', 'Редактировать одно сообщение')], default='edit_single', help_text='Публиковать новые сообщения при каждом обновлении или редактировать одно и то же сообщение', max_length=20, verbose_name='Режим публикации'),
        ),
        migrations.AddField(
            model_name='tournamentannouncementsettings',
            name='last_announcement_message_id',
            field=models.BigIntegerField(blank=True, help_text='ID сообщения в Telegram для режима редактирования', null=True, verbose_name='ID последнего сообщения'),
        ),
    ]
