# Generated by Django 5.2.9 on 2026-02-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_tournamentannouncementsettings_announcement_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='stage_name',
            field=models.CharField(blank=True, default='', help_text="Название стадии (например: 'Предварительная стадия', 'Плей-офф')", max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stage_order',
            field=models.IntegerField(default=0, help_text='Порядковый номер стадии (0 для мастера, 1, 2, 3... для стадий)'),
        ),
    ]
