# Generated by Django 5.2.6 on 2025-10-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tg', 'Telegram'), ('ig', 'Instagram'), ('vk', 'VK'), ('other', 'Другое')], default='tg', max_length=16)),
                ('handle_or_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Соцссылка',
                'verbose_name_plural': 'Соцссылки',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('current_rating', models.IntegerField(default=0, verbose_name='Текущий рейтинг')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень игрока')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Отображаемое имя')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'), models.Index(fields=['display_name'], name='players_pla_display_584b62_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Рейтинг')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='players.player')),
            ],
            options={
                'verbose_name': 'История рейтинга игрока',
                'verbose_name_plural': 'Истории рейтинга игроков',
                'ordering': ['-created_at'],
            },
        ),
    ]
