# Generated by Django 5.2 on 2025-09-20
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('current_rating', models.IntegerField(default=0, verbose_name='Текущий рейтинг')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень игрока')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Отображаемое имя')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tg', 'Telegram'), ('ig', 'Instagram'), ('vk', 'VK'), ('other', 'Другое')], default='tg', max_length=16)),
                ('handle_or_url', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='players.player')),
            ],
            options={
                'verbose_name': 'Соцссылка',
                'verbose_name_plural': 'Соцссылки',
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='players_player_name_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['display_name'], name='players_player_display_idx'),
        ),
    ]
