# Generated by Django 5.2.6 on 2025-10-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerratinghistory',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='players.player'),
        ),
        migrations.AddIndex(
            model_name='playerratinghistory',
            index=models.Index(fields=['player', '-created_at'], name='players_pla_player__a30e88_idx'),
        ),
    ]
