# Generated by Django 5.2.7 on 2025-11-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('tournaments', '0004_ruleset_tournament_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRatingDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_date', models.DateField(blank=True, null=True)),
                ('rating_before', models.FloatField()),
                ('rating_after', models.FloatField()),
                ('total_change', models.FloatField()),
                ('matches_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_dynamic', to='players.player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_dynamic', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Динамика рейтинга игрока (по турнирам)',
                'verbose_name_plural': 'Динамика рейтингов игроков (по турнирам)',
                'ordering': ['player', 'tournament_date', 'id'],
                'indexes': [models.Index(fields=['player', 'tournament_date'], name='players_pla_player__270f53_idx'), models.Index(fields=['tournament_date'], name='players_pla_tournam_dd7170_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'tournament'), name='uniq_player_tournament_dynamic')],
            },
        ),
    ]
