# Generated by Django 5.2.8 on 2025-11-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('tournaments', '0004_ruleset_tournament_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRatingDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.IntegerField()),
                ('rating_after', models.IntegerField()),
                ('total_change', models.IntegerField()),
                ('matches_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_dynamic', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rating_dynamics', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Динамика рейтинга игрока (турнир)',
                'verbose_name_plural': 'Динамики рейтинга игроков (турнир)',
                'ordering': ['player_id', 'tournament_id'],
                'indexes': [models.Index(fields=['player', 'calculated_at'], name='players_pla_player__e456d7_idx'), models.Index(fields=['tournament'], name='players_pla_tournam_14f7de_idx')],
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
