# Generated by Django 5.2.7 on 2025-11-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btr', '0001_initial'),
        ('players', '0003_playerratingdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='btr_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_player', to='btr.btrplayer', verbose_name='Профиль BTR'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=16, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_profi',
            field=models.BooleanField(default=False, verbose_name='Профессиональный игрок (BTR)'),
        ),
        migrations.AddField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
    ]
