# Generated by Django 5.2.9 on 2025-12-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_btr_player_player_gender_player_is_profi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='middle_name',
        ),
    ]
