# Generated by Django 5.2.7 on 2025-11-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtrPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='ID в BTR')),
                ('rni', models.CharField(max_length=64, unique=True, verbose_name='РНИ (номер в BTR)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество/второе имя')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=16, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Игрок BTR',
                'verbose_name_plural': 'Игроки BTR',
            },
        ),
        migrations.CreateModel(
            name='BtrSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL источника')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время скачивания')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Время применения')),
                ('file_hash', models.CharField(blank=True, max_length=128, verbose_name='Хэш содержимого')),
            ],
            options={
                'verbose_name': 'Файл рейтинга BTR',
                'verbose_name_plural': 'Файлы рейтинга BTR',
            },
        ),
        migrations.CreateModel(
            name='BtrRatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('men_double', 'Взрослые, парный, мужчины'), ('men_mixed', 'Взрослые, смешанный, мужчины'), ('women_double', 'Взрослые, парный, женщины'), ('women_mixed', 'Взрослые, смешанный, женщины'), ('junior_male', 'До 19, Юноши'), ('junior_female', 'До 19, Девушки')], max_length=32, verbose_name='Категория')),
                ('rating_date', models.DateField(verbose_name='Дата рейтинга')),
                ('rating_value', models.IntegerField(verbose_name='Значение рейтинга')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Позиция в рейтинге')),
                ('tournaments_total', models.IntegerField(default=0, verbose_name='Турниров всего')),
                ('tournaments_52_weeks', models.IntegerField(default=0, verbose_name='Турниров за 52 недели')),
                ('tournaments_counted', models.IntegerField(default=0, verbose_name='Учтённых турниров')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='btr.btrplayer')),
            ],
            options={
                'verbose_name': 'Снимок рейтинга BTR',
                'verbose_name_plural': 'Снимки рейтинга BTR',
                'indexes': [models.Index(fields=['player', 'category', 'rating_date'], name='btr_btrrati_player__69d573_idx')],
            },
        ),
    ]
