# Generated by Django 5.2.8 on 2025-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrplayer',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='ID в BTR'),
        ),
        migrations.AlterField(
            model_name='btrplayer',
            name='rni',
            field=models.IntegerField(unique=True, verbose_name='РНИ (номер в BTR)'),
        ),
    ]
