# Generated by Django 5.2.6 on 2025-10-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_p1', to='players.player')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_p2', to='players.player')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'constraints': [models.CheckConstraint(condition=models.Q(('player_1', models.F('player_2')), _negated=True), name='team_no_same_players'), models.UniqueConstraint(condition=models.Q(('player_2__isnull', False)), fields=('player_1', 'player_2'), name='unique_team_pair'), models.UniqueConstraint(condition=models.Q(('player_2__isnull', True)), fields=('player_1',), name='unique_single_player_team')],
            },
        ),
    ]
