# Generated by Django 5.2.9 on 2025-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('facilities', models.TextField(blank=True, help_text='Раздевалки, душ, парковка и т.д.', verbose_name='Удобства')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='Фото')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='venues_venu_city_a4d9c1_idx')],
            },
        ),
    ]
