# Generated by Django 5.2.9 on 2026-02-17 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_initial'),
        ('tournaments', '0015_tournament_stage_name_tournament_stage_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match_duration_minutes', models.PositiveSmallIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('first_start_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='schedules.schedule')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('schedule', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleGlobalBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
                ('text', models.CharField(max_length=256)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_breaks', to='schedules.schedule')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('start_mode', models.CharField(choices=[('fixed', 'fixed'), ('then', 'then'), ('not_earlier', 'not_earlier')], default='fixed', max_length=16)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('not_earlier_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='schedules.schedule')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('schedule', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='schedules.schedule')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_scopes', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('schedule', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('match', 'match'), ('text', 'text')], max_length=16)),
                ('text_title', models.CharField(blank=True, max_length=256, null=True)),
                ('text_subtitle', models.TextField(blank=True, null=True)),
                ('override_title', models.CharField(blank=True, max_length=256, null=True)),
                ('override_subtitle', models.TextField(blank=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.schedulecourt')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='matches.match')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.schedulerun')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'run', 'court')},
            },
        ),
    ]
