# Generated by Django 5.2.11 on 2026-03-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescope',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedulescope',
            name='start_mode',
            field=models.CharField(choices=[('fixed', 'fixed'), ('after_previous', 'after_previous')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulescope',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleScopeCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_to_scopes', to='schedules.schedulecourt')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_courts', to='schedules.schedulescope')),
            ],
            options={
                'unique_together': {('scope', 'court')},
            },
        ),
    ]
