# Generated by Django 5.2.11 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_default_wave(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")
    ScheduleWave = apps.get_model("schedules", "ScheduleWave")
    ScheduleScope = apps.get_model("schedules", "ScheduleScope")

    for sch in Schedule.objects.all().iterator():
        wave = ScheduleWave.objects.filter(schedule_id=sch.id).order_by("order", "id").first()
        if not wave:
            wave = ScheduleWave.objects.create(
                schedule_id=sch.id,
                order=1,
                start_mode="after_previous",
                start_time=None,
                earliest_time=None,
            )
        ScheduleScope.objects.filter(schedule_id=sch.id, wave__isnull=True).update(wave_id=wave.id)


def backwards_clear_wave(apps, schema_editor):
    ScheduleScope = apps.get_model("schedules", "ScheduleScope")
    ScheduleScope.objects.all().update(wave_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedulescope_order_schedulescope_start_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleWave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "start_mode",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("after_previous", "after_previous")],
                        default="after_previous",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("earliest_time", models.TimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waves",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="schedulescope",
            name="wave",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="schedules.schedulewave",
            ),
        ),
        migrations.RunPython(forwards_create_default_wave, backwards_clear_wave),
    ]
