# Generated by Django 5.2.9 on 2025-12-09 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0004_player_btr_player_player_gender_player_is_profi_and_more'),
        ('tournaments', '0007_remove_tournamententry_unique_entry_position_and_more'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('notify_tournament_open', models.BooleanField(default=True, verbose_name='Открытие регистрации')),
                ('notify_tournament_start', models.BooleanField(default=True, verbose_name='Старт турнира')),
                ('notify_match_start', models.BooleanField(default=True, verbose_name='Начало матча')),
                ('notify_match_result', models.BooleanField(default=True, verbose_name='Результат матча')),
                ('notify_rating_change', models.BooleanField(default=True, verbose_name='Изменение рейтинга')),
                ('notify_pair_request', models.BooleanField(default=True, verbose_name='Запрос на пару')),
                ('language_code', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокировал бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Последнее взаимодействие')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to='players.player', verbose_name='Игрок')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_requests', to='tournaments.tournament', verbose_name='Турнир')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pair_requests', to='telegram_bot.telegramuser', verbose_name='От кого')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pair_requests', to='telegram_bot.telegramuser', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Запрос на пару',
                'verbose_name_plural': 'Запросы на пару',
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50, verbose_name='Тип уведомления')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Турнир')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.telegramuser', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['telegram_user', '-sent_at'], name='telegram_bo_telegra_884af8_idx'), models.Index(fields=['notification_type', '-sent_at'], name='telegram_bo_notific_be998a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telegram_bot.telegramuser', verbose_name='Telegram пользователь')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscribers', to='venues.venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
                'unique_together': {('telegram_user', 'organizer'), ('telegram_user', 'venue')},
            },
        ),
    ]
