# Generated by Django 5.2 on 2025-09-20
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_name", models.CharField(blank=True, max_length=50, null=True)),
                ("order_in_round", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tournament",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="tournaments.tournament"),
                ),
                (
                    "team_1",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="matches_as_team1", to="teams.team"),
                ),
                (
                    "team_2",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="matches_as_team2", to="teams.team"),
                ),
                (
                    "winner",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wins", to="teams.team"),
                ),
            ],
            options={
                "verbose_name": "Матч",
                "verbose_name_plural": "Матчи",
            },
        ),
        migrations.CreateModel(
            name="MatchSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveSmallIntegerField()),
                ("games_1", models.PositiveSmallIntegerField(default=0)),
                ("games_2", models.PositiveSmallIntegerField(default=0)),
                ("tb_1", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tb_2", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "is_tiebreak_only",
                    models.BooleanField(default=False, help_text="Если True — это сет-тайбрейк (например, до 10)"),
                ),
                (
                    "match",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sets", to="matches.match"),
                ),
            ],
            options={
                "ordering": ["match", "index"],
                "verbose_name": "Сет матча",
                "verbose_name_plural": "Сеты матча",
                "unique_together": {("match", "index")},
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["tournament", "round_name", "order_in_round"], name="matches_mat_tournam_953070_idx"),
        ),
    ]
