# Generated by Django 5.2.6 on 2025-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Групповой этап'), ('playoff', 'Плей-офф'), ('placement', 'Классификация')], default='group', max_length=16)),
                ('group_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order_in_round', models.IntegerField(default=0)),
                ('is_third_place', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('live', 'Идёт'), ('completed', 'Завершён'), ('walkover', 'Неявка'), ('retired', 'Снятие'), ('default', 'Дисквалификация')], default='scheduled', max_length=16)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('games_1', models.PositiveSmallIntegerField(default=0)),
                ('games_2', models.PositiveSmallIntegerField(default=0)),
                ('tb_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tb_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_tiebreak_only', models.BooleanField(default=False, help_text='Если True — это сет-тайбрейк (например, до 10)')),
            ],
            options={
                'verbose_name': 'Сет матча',
                'verbose_name_plural': 'Сеты матча',
                'ordering': ['match', 'index'],
            },
        ),
        migrations.CreateModel(
            name='MatchSpecialOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('walkover', 'Неявка'), ('retired', 'Снятие'), ('default', 'Дисквалификация')], max_length=16)),
                ('set_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_at_stop', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Особый исход матча',
                'verbose_name_plural': 'Особые исходы матча',
            },
        ),
    ]
