# Generated by Django 5.2 on 2025-09-20
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('group', 'Групповой этап'), ('playoff', 'Плей-офф'), ('placement', 'Классификация')], default='group', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='group_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('live', 'Идёт'), ('completed', 'Завершён'), ('walkover', 'Неявка'), ('retired', 'Снятие'), ('default', 'Дисквалификация')], default='scheduled', max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_low', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_high', to='teams.team'),
        ),
        migrations.CreateModel(
            name='MatchSpecialOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('walkover', 'Неявка'), ('retired', 'Снятие'), ('default', 'Дисквалификация')], max_length=16)),
                ('set_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_at_stop', models.CharField(blank=True, max_length=20, null=True)),
                ('defaulted_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaulted_in_matches', to='teams.team')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_outcome', to='matches.match')),
                ('retired_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_in_matches', to='teams.team')),
            ],
            options={
                'verbose_name': 'Особый исход матча',
                'verbose_name_plural': 'Особые исходы матча',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_match_tournament_status_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'winner'], name='matches_match_tournament_winner_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'team_low'], name='matches_match_tournament_team_low_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'team_high'], name='matches_match_tournament_team_high_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'stage', 'group_index', 'round_index', 'order_in_round'], name='matches_match_stage_group_round_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'stage', 'group_index', 'team_low', 'team_high'), name='uniq_match_pair_in_stage_group'),
        ),
    ]
