# Generated by Django 5.2.6 on 2025-10-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.knockoutbracket'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team1', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team2', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_high', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_low', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchset',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchspecialoutcome',
            name='defaulted_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaulted_in_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchspecialoutcome',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_outcome', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchspecialoutcome',
            name='retired_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_in_matches', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_name', 'order_in_round'], name='matches_mat_tournam_953070_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_mat_tournam_bfa07e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'winner'], name='matches_mat_tournam_ccff4b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'team_low'], name='matches_mat_tournam_16ff24_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'team_high'], name='matches_mat_tournam_6d4a11_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'stage', 'group_index', 'round_index', 'order_in_round'], name='matches_mat_tournam_cd5997_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'stage', 'bracket', 'round_index', 'order_in_round'], name='matches_mat_tournam_3918f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'stage', 'group_index', 'team_low', 'team_high'), name='uniq_match_pair_in_stage_group'),
        ),
        migrations.AlterUniqueTogether(
            name='matchset',
            unique_together={('match', 'index')},
        ),
    ]
