# Generated by Cascade: state-only migration linking Match to KnockoutBracket
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_add_extended_fields"),
        ("tournaments", "0003_knockout_models_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="match",
                    name="bracket",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="matches", to="tournaments.knockoutbracket"),
                ),
                migrations.AddField(
                    model_name="match",
                    name="is_third_place",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddIndex(
                    model_name="match",
                    index=models.Index(fields=["tournament", "stage", "bracket", "round_index", "order_in_round"], name="matches_mat_tourn_s_4a1c6f_idx"),
                ),
            ],
        )
    ]
