# Generated by Django 5.2.6 on 2025-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_allow_null_teams_in_match'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_bfa07e_idx',
            old_name='matches_match_tournament_status_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_ccff4b_idx',
            old_name='matches_match_tournament_winner_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_16ff24_idx',
            old_name='matches_match_tournament_team_low_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_6d4a11_idx',
            old_name='matches_match_tournament_team_high_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_cd5997_idx',
            old_name='matches_match_stage_group_round_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_tournam_3918f0_idx',
            old_name='matches_mat_tourn_s_4a1c6f_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchspecialoutcome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
